PointfootCfg:
  loop_frequency: 500
  joint_names:
    - "abad_L_Joint"
    - "hip_L_Joint"
    - "knee_L_Joint"
    - "ankle_L_Joint"
    - "abad_R_Joint"
    - "hip_R_Joint"
    - "knee_R_Joint"
    - "ankle_R_Joint"

  # Joint limits from URDF (in radians)
  joint_limits:
    abad_L_Joint:
      lower: -0.38397    # -22 degrees
      upper: 1.39626     # 80 degrees
      effort: 80.0
      velocity: 15.0
    hip_L_Joint:
      lower: -1.012291   # -58 degrees
      upper: 1.396263    # 80 degrees
      effort: 80.0
      velocity: 15.0
    knee_L_Joint:
      lower: -0.872665   # -50 degrees
      upper: 1.361357    # 78 degrees
      effort: 80.0
      velocity: 15.0
    ankle_L_Joint:
      lower: -1.15191730631626  # -66 degrees
      upper: 1.5707963267949    # 90 degrees
      effort: 20.0
      velocity: 15.0
    abad_R_Joint:
      lower: -1.39626    # -80 degrees
      upper: 0.38397     # 22 degrees
      effort: 80.0
      velocity: 15.0
    hip_R_Joint:
      lower: -1.396263   # -80 degrees
      upper: 1.012291    # 58 degrees
      effort: 80.0
      velocity: 15.0
    knee_R_Joint:
      lower: -1.361357   # -78 degrees
      upper: 0.872665    # 50 degrees
      effort: 80.0
      velocity: 15.0
    ankle_R_Joint:
      lower: -1.15191730631626  # -66 degrees
      upper: 1.5707963267949    # 90 degrees
      effort: 20.0
      velocity: 15.0

  init_state:
    # target angles [rad] when action = 0.0
    # Updated based on joint limits for safe initialization
    default_joint_angle:
      abad_L_Joint: 0.5      # Mid-range of [-0.38397, 1.39626]
      hip_L_Joint: 0.19      # Slightly positive for natural stance
      knee_L_Joint: 0.24     # Slightly bent knee for stability
      ankle_L_Joint: 0.18    # Slight forward lean

      abad_R_Joint: -0.5     # Mid-range of [-1.39626, 0.38397]
      hip_R_Joint: -0.19     # Mirror of left side
      knee_R_Joint: -0.24    # Mirror of left side
      ankle_R_Joint: 0.18    # Same as left side

  control:
    # PD Drive parameters based on URDF effort limits:
    stiffness: 45.0
    damping: 3.0
    ankle_joint_damping: 1.5    # Lower damping for ankle joints
    ankle_joint_torque_limit: 20  # From URDF ankle effort limit
    action_scale_pos: 0.25
    decimation: 10
    user_torque_limit: 80       # From URDF main joint effort limits

  normalization:
    clip_scales:
      clip_observations: 100.
      clip_actions: 100.
    obs_scales:
      lin_vel: 2.0
      ang_vel: 0.25
      dof_pos: 1.0
      dof_vel: 0.05

  size:
    actions_size: 8
    observations_size: 36
    obs_history_length: 5
    encoder_output_size: 3
    commands_size: 5

  gait:
    frequencies: 1.3
    swing_height: 0.12

  stand_mode:
    stand_duration: 1.0

  imu_orientation_offset:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  user_cmd_scales:
    lin_vel_x: 1.0
    lin_vel_y: 0.5
    ang_vel_yaw: 1.0
